# Generated by Django 4.0.4 on 2022-04-23 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=180, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('payment_rate', models.FloatField()),
                ('is_manager', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonusCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_compensation', models.FloatField()),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contact_person', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=120)),
                ('rating', models.IntegerField()),
                ('employees_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationalCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_compensation', models.FloatField()),
                ('institution', models.CharField(max_length=50)),
                ('issue_date', models.DateTimeField()),
                ('course_name', models.CharField(max_length=50)),
                ('certificate_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_compensation', models.FloatField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('hospital', models.CharField(max_length=50)),
                ('medical_statement_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SportCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_compensation', models.FloatField()),
                ('gym', models.CharField(max_length=50)),
                ('receipt_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('asigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensations.project')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeWorkCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_amount', models.FloatField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compensations.task')),
            ],
        ),
        migrations.CreateModel(
            name='CompensationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('compensation_type', models.CharField(choices=[('bonus', 'Bonus'), ('medical', 'Medical'), ('educational', 'Educational'), ('sport', 'Sport'), ('overtime', 'Overtime')], max_length=30)),
                ('compensation_info_id', models.IntegerField()),
                ('empoloyee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
