# Generated by Django 4.0.4 on 2022-04-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
