# Generated by Django 4.0.4 on 2022-04-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0002_compensationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationrequest',
            name='compensation_info_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='in progress', max_length=20),
        ),
    ]
