# Generated by Django 4.0.4 on 2022-04-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0003_alter_compensationrequest_compensation_info_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compensations.project'),
        ),
    ]
