# Generated by Django 4.0.4 on 2022-04-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0004_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
