# Generated by Django 4.0.4 on 2022-04-24 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0005_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationrequest',
            name='empoloyee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
