# Generated by Django 4.0.4 on 2022-04-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0006_alter_compensationrequest_empoloyee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensationrequest',
            old_name='empoloyee',
            new_name='employee',
        ),
    ]
