# Generated by Django 4.0.4 on 2022-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0007_rename_empoloyee_compensationrequest_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcompensation',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicalcompensation',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
