# Generated by Django 4.0.4 on 2022-04-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0008_alter_medicalcompensation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationrequest',
            name='requested_compensation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='compensationrequest',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
