# Generated by Django 4.0.4 on 2022-04-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0009_compensationrequest_requested_compensation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationrequest',
            name='date_str',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compensationrequest',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
