# Generated by Django 4.0.4 on 2022-04-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensations', '0010_compensationrequest_date_str_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalcompensation',
            old_name='certificate_url',
            new_name='proof_url',
        ),
        migrations.RenameField(
            model_name='medicalcompensation',
            old_name='medical_statement_url',
            new_name='proof_url',
        ),
        migrations.RenameField(
            model_name='sportcompensation',
            old_name='receipt_url',
            new_name='proof_url',
        ),
        migrations.AddField(
            model_name='bonuscompensation',
            name='proof_url',
            field=models.CharField(default='https://proof-url', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compensationrequest',
            name='proof_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
